version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: srikanth
      MONGO_INITDB_ROOT_PASSWORD: Rajini@123

volumes:
  mongodb_data:
